/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VillesRouteImport } from './routes/villes'
import { Route as TarifsRouteImport } from './routes/tarifs'
import { Route as SinistresRouteImport } from './routes/sinistres'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LoginRouteImport } from './routes/login'
import { Route as InscriptionExpertRouteImport } from './routes/inscription-expert'
import { Route as GuidesRouteImport } from './routes/guides'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as ExpertsRouteImport } from './routes/experts'
import { Route as ExpertAssureToulouseRouteImport } from './routes/expert-assure-toulouse'
import { Route as ExpertAssureParisRouteImport } from './routes/expert-assure-paris'
import { Route as ExpertAssureMarseilleRouteImport } from './routes/expert-assure-marseille'
import { Route as ExpertAssureLyonRouteImport } from './routes/expert-assure-lyon'
import { Route as ExpertAssureBordeauxRouteImport } from './routes/expert-assure-bordeaux'
import { Route as ExpertRouteImport } from './routes/expert'
import { Route as EspaceRouteImport } from './routes/espace'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CommentCaMarcheRouteImport } from './routes/comment-ca-marche'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AProposRouteImport } from './routes/a-propos'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SinistresIndexRouteImport } from './routes/sinistres.index'
import { Route as GuidesIndexRouteImport } from './routes/guides.index'
import { Route as ExpertIndexRouteImport } from './routes/expert.index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as SinistresTempeteRouteImport } from './routes/sinistres.tempete'
import { Route as SinistresIncendieRouteImport } from './routes/sinistres.incendie'
import { Route as SinistresDommagesElectriquesRouteImport } from './routes/sinistres.dommages-electriques'
import { Route as SinistresDegatDesEauxRouteImport } from './routes/sinistres.degat-des-eaux'
import { Route as SinistresCatastropheNaturelleRouteImport } from './routes/sinistres.catastrophe-naturelle'
import { Route as GuidesVetusteAssuranceRouteImport } from './routes/guides.vetuste-assurance'
import { Route as GuidesSousIndemnisationRouteImport } from './routes/guides.sous-indemnisation'
import { Route as GuidesRegleProportionnelleAssuranceRouteImport } from './routes/guides.regle-proportionnelle-assurance'
import { Route as GuidesProcesVerbalExpertiseAssuranceRouteImport } from './routes/guides.proces-verbal-expertise-assurance'
import { Route as GuidesExpertAssureRouteImport } from './routes/guides.expert-assure'
import { Route as GuidesDelaiPrescriptionAssuranceRouteImport } from './routes/guides.delai-prescription-assurance'
import { Route as GuidesDeclarerSinistreAssuranceRouteImport } from './routes/guides.declarer-sinistre-assurance'
import { Route as GuidesAssureurRefusePayerRouteImport } from './routes/guides.assureur-refuse-payer'
import { Route as ExpertProfilRouteImport } from './routes/expert.profil'
import { Route as ExpertDossiersRouteImport } from './routes/expert.dossiers'
import { Route as EspaceNouveauRouteImport } from './routes/espace.nouveau'
import { Route as EspaceDossiersRouteImport } from './routes/espace.dossiers'
import { Route as DashboardNouveauRouteImport } from './routes/dashboard.nouveau'
import { Route as AdminUtilisateursRouteImport } from './routes/admin.utilisateurs'
import { Route as AdminReportingRouteImport } from './routes/admin.reporting'
import { Route as AdminFacturationRouteImport } from './routes/admin.facturation'
import { Route as AdminExpertsRouteImport } from './routes/admin.experts'
import { Route as AdminDossiersRouteImport } from './routes/admin.dossiers'
import { Route as ExpertDossiersIndexRouteImport } from './routes/expert.dossiers.index'
import { Route as AdminDossiersIndexRouteImport } from './routes/admin.dossiers.index'
import { Route as ExpertDossiersIdRouteImport } from './routes/expert.dossiers.$id'
import { Route as EspaceDossiersCaseIdRouteImport } from './routes/espace.dossiers.$caseId'
import { Route as DashboardDossiersIdRouteImport } from './routes/dashboard.dossiers.$id'
import { Route as AdminUtilisateursUserIdRouteImport } from './routes/admin_.utilisateurs.$userId'
import { Route as AdminDossiersDossierIdRouteImport } from './routes/admin.dossiers.$dossierId'

const VillesRoute = VillesRouteImport.update({
  id: '/villes',
  path: '/villes',
  getParentRoute: () => rootRouteImport,
} as any)
const TarifsRoute = TarifsRouteImport.update({
  id: '/tarifs',
  path: '/tarifs',
  getParentRoute: () => rootRouteImport,
} as any)
const SinistresRoute = SinistresRouteImport.update({
  id: '/sinistres',
  path: '/sinistres',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const InscriptionExpertRoute = InscriptionExpertRouteImport.update({
  id: '/inscription-expert',
  path: '/inscription-expert',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidesRoute = GuidesRouteImport.update({
  id: '/guides',
  path: '/guides',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const ExpertsRoute = ExpertsRouteImport.update({
  id: '/experts',
  path: '/experts',
  getParentRoute: () => rootRouteImport,
} as any)
const ExpertAssureToulouseRoute = ExpertAssureToulouseRouteImport.update({
  id: '/expert-assure-toulouse',
  path: '/expert-assure-toulouse',
  getParentRoute: () => rootRouteImport,
} as any)
const ExpertAssureParisRoute = ExpertAssureParisRouteImport.update({
  id: '/expert-assure-paris',
  path: '/expert-assure-paris',
  getParentRoute: () => rootRouteImport,
} as any)
const ExpertAssureMarseilleRoute = ExpertAssureMarseilleRouteImport.update({
  id: '/expert-assure-marseille',
  path: '/expert-assure-marseille',
  getParentRoute: () => rootRouteImport,
} as any)
const ExpertAssureLyonRoute = ExpertAssureLyonRouteImport.update({
  id: '/expert-assure-lyon',
  path: '/expert-assure-lyon',
  getParentRoute: () => rootRouteImport,
} as any)
const ExpertAssureBordeauxRoute = ExpertAssureBordeauxRouteImport.update({
  id: '/expert-assure-bordeaux',
  path: '/expert-assure-bordeaux',
  getParentRoute: () => rootRouteImport,
} as any)
const ExpertRoute = ExpertRouteImport.update({
  id: '/expert',
  path: '/expert',
  getParentRoute: () => rootRouteImport,
} as any)
const EspaceRoute = EspaceRouteImport.update({
  id: '/espace',
  path: '/espace',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CommentCaMarcheRoute = CommentCaMarcheRouteImport.update({
  id: '/comment-ca-marche',
  path: '/comment-ca-marche',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AProposRoute = AProposRouteImport.update({
  id: '/a-propos',
  path: '/a-propos',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SinistresIndexRoute = SinistresIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SinistresRoute,
} as any)
const GuidesIndexRoute = GuidesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => GuidesRoute,
} as any)
const ExpertIndexRoute = ExpertIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ExpertRoute,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const SinistresTempeteRoute = SinistresTempeteRouteImport.update({
  id: '/tempete',
  path: '/tempete',
  getParentRoute: () => SinistresRoute,
} as any)
const SinistresIncendieRoute = SinistresIncendieRouteImport.update({
  id: '/incendie',
  path: '/incendie',
  getParentRoute: () => SinistresRoute,
} as any)
const SinistresDommagesElectriquesRoute =
  SinistresDommagesElectriquesRouteImport.update({
    id: '/dommages-electriques',
    path: '/dommages-electriques',
    getParentRoute: () => SinistresRoute,
  } as any)
const SinistresDegatDesEauxRoute = SinistresDegatDesEauxRouteImport.update({
  id: '/degat-des-eaux',
  path: '/degat-des-eaux',
  getParentRoute: () => SinistresRoute,
} as any)
const SinistresCatastropheNaturelleRoute =
  SinistresCatastropheNaturelleRouteImport.update({
    id: '/catastrophe-naturelle',
    path: '/catastrophe-naturelle',
    getParentRoute: () => SinistresRoute,
  } as any)
const GuidesVetusteAssuranceRoute = GuidesVetusteAssuranceRouteImport.update({
  id: '/vetuste-assurance',
  path: '/vetuste-assurance',
  getParentRoute: () => GuidesRoute,
} as any)
const GuidesSousIndemnisationRoute = GuidesSousIndemnisationRouteImport.update({
  id: '/sous-indemnisation',
  path: '/sous-indemnisation',
  getParentRoute: () => GuidesRoute,
} as any)
const GuidesRegleProportionnelleAssuranceRoute =
  GuidesRegleProportionnelleAssuranceRouteImport.update({
    id: '/regle-proportionnelle-assurance',
    path: '/regle-proportionnelle-assurance',
    getParentRoute: () => GuidesRoute,
  } as any)
const GuidesProcesVerbalExpertiseAssuranceRoute =
  GuidesProcesVerbalExpertiseAssuranceRouteImport.update({
    id: '/proces-verbal-expertise-assurance',
    path: '/proces-verbal-expertise-assurance',
    getParentRoute: () => GuidesRoute,
  } as any)
const GuidesExpertAssureRoute = GuidesExpertAssureRouteImport.update({
  id: '/expert-assure',
  path: '/expert-assure',
  getParentRoute: () => GuidesRoute,
} as any)
const GuidesDelaiPrescriptionAssuranceRoute =
  GuidesDelaiPrescriptionAssuranceRouteImport.update({
    id: '/delai-prescription-assurance',
    path: '/delai-prescription-assurance',
    getParentRoute: () => GuidesRoute,
  } as any)
const GuidesDeclarerSinistreAssuranceRoute =
  GuidesDeclarerSinistreAssuranceRouteImport.update({
    id: '/declarer-sinistre-assurance',
    path: '/declarer-sinistre-assurance',
    getParentRoute: () => GuidesRoute,
  } as any)
const GuidesAssureurRefusePayerRoute =
  GuidesAssureurRefusePayerRouteImport.update({
    id: '/assureur-refuse-payer',
    path: '/assureur-refuse-payer',
    getParentRoute: () => GuidesRoute,
  } as any)
const ExpertProfilRoute = ExpertProfilRouteImport.update({
  id: '/profil',
  path: '/profil',
  getParentRoute: () => ExpertRoute,
} as any)
const ExpertDossiersRoute = ExpertDossiersRouteImport.update({
  id: '/dossiers',
  path: '/dossiers',
  getParentRoute: () => ExpertRoute,
} as any)
const EspaceNouveauRoute = EspaceNouveauRouteImport.update({
  id: '/nouveau',
  path: '/nouveau',
  getParentRoute: () => EspaceRoute,
} as any)
const EspaceDossiersRoute = EspaceDossiersRouteImport.update({
  id: '/dossiers',
  path: '/dossiers',
  getParentRoute: () => EspaceRoute,
} as any)
const DashboardNouveauRoute = DashboardNouveauRouteImport.update({
  id: '/nouveau',
  path: '/nouveau',
  getParentRoute: () => DashboardRoute,
} as any)
const AdminUtilisateursRoute = AdminUtilisateursRouteImport.update({
  id: '/utilisateurs',
  path: '/utilisateurs',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReportingRoute = AdminReportingRouteImport.update({
  id: '/reporting',
  path: '/reporting',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFacturationRoute = AdminFacturationRouteImport.update({
  id: '/facturation',
  path: '/facturation',
  getParentRoute: () => AdminRoute,
} as any)
const AdminExpertsRoute = AdminExpertsRouteImport.update({
  id: '/experts',
  path: '/experts',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDossiersRoute = AdminDossiersRouteImport.update({
  id: '/dossiers',
  path: '/dossiers',
  getParentRoute: () => AdminRoute,
} as any)
const ExpertDossiersIndexRoute = ExpertDossiersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ExpertDossiersRoute,
} as any)
const AdminDossiersIndexRoute = AdminDossiersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminDossiersRoute,
} as any)
const ExpertDossiersIdRoute = ExpertDossiersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ExpertDossiersRoute,
} as any)
const EspaceDossiersCaseIdRoute = EspaceDossiersCaseIdRouteImport.update({
  id: '/$caseId',
  path: '/$caseId',
  getParentRoute: () => EspaceDossiersRoute,
} as any)
const DashboardDossiersIdRoute = DashboardDossiersIdRouteImport.update({
  id: '/dossiers/$id',
  path: '/dossiers/$id',
  getParentRoute: () => DashboardRoute,
} as any)
const AdminUtilisateursUserIdRoute = AdminUtilisateursUserIdRouteImport.update({
  id: '/admin_/utilisateurs/$userId',
  path: '/admin/utilisateurs/$userId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDossiersDossierIdRoute = AdminDossiersDossierIdRouteImport.update({
  id: '/$dossierId',
  path: '/$dossierId',
  getParentRoute: () => AdminDossiersRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/comment-ca-marche': typeof CommentCaMarcheRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/espace': typeof EspaceRouteWithChildren
  '/expert': typeof ExpertRouteWithChildren
  '/expert-assure-bordeaux': typeof ExpertAssureBordeauxRoute
  '/expert-assure-lyon': typeof ExpertAssureLyonRoute
  '/expert-assure-marseille': typeof ExpertAssureMarseilleRoute
  '/expert-assure-paris': typeof ExpertAssureParisRoute
  '/expert-assure-toulouse': typeof ExpertAssureToulouseRoute
  '/experts': typeof ExpertsRoute
  '/faq': typeof FaqRoute
  '/guides': typeof GuidesRouteWithChildren
  '/inscription-expert': typeof InscriptionExpertRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sinistres': typeof SinistresRouteWithChildren
  '/tarifs': typeof TarifsRoute
  '/villes': typeof VillesRoute
  '/admin/dossiers': typeof AdminDossiersRouteWithChildren
  '/admin/experts': typeof AdminExpertsRoute
  '/admin/facturation': typeof AdminFacturationRoute
  '/admin/reporting': typeof AdminReportingRoute
  '/admin/utilisateurs': typeof AdminUtilisateursRoute
  '/dashboard/nouveau': typeof DashboardNouveauRoute
  '/espace/dossiers': typeof EspaceDossiersRouteWithChildren
  '/espace/nouveau': typeof EspaceNouveauRoute
  '/expert/dossiers': typeof ExpertDossiersRouteWithChildren
  '/expert/profil': typeof ExpertProfilRoute
  '/guides/assureur-refuse-payer': typeof GuidesAssureurRefusePayerRoute
  '/guides/declarer-sinistre-assurance': typeof GuidesDeclarerSinistreAssuranceRoute
  '/guides/delai-prescription-assurance': typeof GuidesDelaiPrescriptionAssuranceRoute
  '/guides/expert-assure': typeof GuidesExpertAssureRoute
  '/guides/proces-verbal-expertise-assurance': typeof GuidesProcesVerbalExpertiseAssuranceRoute
  '/guides/regle-proportionnelle-assurance': typeof GuidesRegleProportionnelleAssuranceRoute
  '/guides/sous-indemnisation': typeof GuidesSousIndemnisationRoute
  '/guides/vetuste-assurance': typeof GuidesVetusteAssuranceRoute
  '/sinistres/catastrophe-naturelle': typeof SinistresCatastropheNaturelleRoute
  '/sinistres/degat-des-eaux': typeof SinistresDegatDesEauxRoute
  '/sinistres/dommages-electriques': typeof SinistresDommagesElectriquesRoute
  '/sinistres/incendie': typeof SinistresIncendieRoute
  '/sinistres/tempete': typeof SinistresTempeteRoute
  '/admin/': typeof AdminIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/expert/': typeof ExpertIndexRoute
  '/guides/': typeof GuidesIndexRoute
  '/sinistres/': typeof SinistresIndexRoute
  '/admin/dossiers/$dossierId': typeof AdminDossiersDossierIdRoute
  '/admin/utilisateurs/$userId': typeof AdminUtilisateursUserIdRoute
  '/dashboard/dossiers/$id': typeof DashboardDossiersIdRoute
  '/espace/dossiers/$caseId': typeof EspaceDossiersCaseIdRoute
  '/expert/dossiers/$id': typeof ExpertDossiersIdRoute
  '/admin/dossiers/': typeof AdminDossiersIndexRoute
  '/expert/dossiers/': typeof ExpertDossiersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/auth': typeof AuthRoute
  '/comment-ca-marche': typeof CommentCaMarcheRoute
  '/contact': typeof ContactRoute
  '/espace': typeof EspaceRouteWithChildren
  '/expert-assure-bordeaux': typeof ExpertAssureBordeauxRoute
  '/expert-assure-lyon': typeof ExpertAssureLyonRoute
  '/expert-assure-marseille': typeof ExpertAssureMarseilleRoute
  '/expert-assure-paris': typeof ExpertAssureParisRoute
  '/expert-assure-toulouse': typeof ExpertAssureToulouseRoute
  '/experts': typeof ExpertsRoute
  '/faq': typeof FaqRoute
  '/inscription-expert': typeof InscriptionExpertRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/tarifs': typeof TarifsRoute
  '/villes': typeof VillesRoute
  '/admin/experts': typeof AdminExpertsRoute
  '/admin/facturation': typeof AdminFacturationRoute
  '/admin/reporting': typeof AdminReportingRoute
  '/admin/utilisateurs': typeof AdminUtilisateursRoute
  '/dashboard/nouveau': typeof DashboardNouveauRoute
  '/espace/dossiers': typeof EspaceDossiersRouteWithChildren
  '/espace/nouveau': typeof EspaceNouveauRoute
  '/expert/profil': typeof ExpertProfilRoute
  '/guides/assureur-refuse-payer': typeof GuidesAssureurRefusePayerRoute
  '/guides/declarer-sinistre-assurance': typeof GuidesDeclarerSinistreAssuranceRoute
  '/guides/delai-prescription-assurance': typeof GuidesDelaiPrescriptionAssuranceRoute
  '/guides/expert-assure': typeof GuidesExpertAssureRoute
  '/guides/proces-verbal-expertise-assurance': typeof GuidesProcesVerbalExpertiseAssuranceRoute
  '/guides/regle-proportionnelle-assurance': typeof GuidesRegleProportionnelleAssuranceRoute
  '/guides/sous-indemnisation': typeof GuidesSousIndemnisationRoute
  '/guides/vetuste-assurance': typeof GuidesVetusteAssuranceRoute
  '/sinistres/catastrophe-naturelle': typeof SinistresCatastropheNaturelleRoute
  '/sinistres/degat-des-eaux': typeof SinistresDegatDesEauxRoute
  '/sinistres/dommages-electriques': typeof SinistresDommagesElectriquesRoute
  '/sinistres/incendie': typeof SinistresIncendieRoute
  '/sinistres/tempete': typeof SinistresTempeteRoute
  '/admin': typeof AdminIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/expert': typeof ExpertIndexRoute
  '/guides': typeof GuidesIndexRoute
  '/sinistres': typeof SinistresIndexRoute
  '/admin/dossiers/$dossierId': typeof AdminDossiersDossierIdRoute
  '/admin/utilisateurs/$userId': typeof AdminUtilisateursUserIdRoute
  '/dashboard/dossiers/$id': typeof DashboardDossiersIdRoute
  '/espace/dossiers/$caseId': typeof EspaceDossiersCaseIdRoute
  '/expert/dossiers/$id': typeof ExpertDossiersIdRoute
  '/admin/dossiers': typeof AdminDossiersIndexRoute
  '/expert/dossiers': typeof ExpertDossiersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/comment-ca-marche': typeof CommentCaMarcheRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/espace': typeof EspaceRouteWithChildren
  '/expert': typeof ExpertRouteWithChildren
  '/expert-assure-bordeaux': typeof ExpertAssureBordeauxRoute
  '/expert-assure-lyon': typeof ExpertAssureLyonRoute
  '/expert-assure-marseille': typeof ExpertAssureMarseilleRoute
  '/expert-assure-paris': typeof ExpertAssureParisRoute
  '/expert-assure-toulouse': typeof ExpertAssureToulouseRoute
  '/experts': typeof ExpertsRoute
  '/faq': typeof FaqRoute
  '/guides': typeof GuidesRouteWithChildren
  '/inscription-expert': typeof InscriptionExpertRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sinistres': typeof SinistresRouteWithChildren
  '/tarifs': typeof TarifsRoute
  '/villes': typeof VillesRoute
  '/admin/dossiers': typeof AdminDossiersRouteWithChildren
  '/admin/experts': typeof AdminExpertsRoute
  '/admin/facturation': typeof AdminFacturationRoute
  '/admin/reporting': typeof AdminReportingRoute
  '/admin/utilisateurs': typeof AdminUtilisateursRoute
  '/dashboard/nouveau': typeof DashboardNouveauRoute
  '/espace/dossiers': typeof EspaceDossiersRouteWithChildren
  '/espace/nouveau': typeof EspaceNouveauRoute
  '/expert/dossiers': typeof ExpertDossiersRouteWithChildren
  '/expert/profil': typeof ExpertProfilRoute
  '/guides/assureur-refuse-payer': typeof GuidesAssureurRefusePayerRoute
  '/guides/declarer-sinistre-assurance': typeof GuidesDeclarerSinistreAssuranceRoute
  '/guides/delai-prescription-assurance': typeof GuidesDelaiPrescriptionAssuranceRoute
  '/guides/expert-assure': typeof GuidesExpertAssureRoute
  '/guides/proces-verbal-expertise-assurance': typeof GuidesProcesVerbalExpertiseAssuranceRoute
  '/guides/regle-proportionnelle-assurance': typeof GuidesRegleProportionnelleAssuranceRoute
  '/guides/sous-indemnisation': typeof GuidesSousIndemnisationRoute
  '/guides/vetuste-assurance': typeof GuidesVetusteAssuranceRoute
  '/sinistres/catastrophe-naturelle': typeof SinistresCatastropheNaturelleRoute
  '/sinistres/degat-des-eaux': typeof SinistresDegatDesEauxRoute
  '/sinistres/dommages-electriques': typeof SinistresDommagesElectriquesRoute
  '/sinistres/incendie': typeof SinistresIncendieRoute
  '/sinistres/tempete': typeof SinistresTempeteRoute
  '/admin/': typeof AdminIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/expert/': typeof ExpertIndexRoute
  '/guides/': typeof GuidesIndexRoute
  '/sinistres/': typeof SinistresIndexRoute
  '/admin/dossiers/$dossierId': typeof AdminDossiersDossierIdRoute
  '/admin_/utilisateurs/$userId': typeof AdminUtilisateursUserIdRoute
  '/dashboard/dossiers/$id': typeof DashboardDossiersIdRoute
  '/espace/dossiers/$caseId': typeof EspaceDossiersCaseIdRoute
  '/expert/dossiers/$id': typeof ExpertDossiersIdRoute
  '/admin/dossiers/': typeof AdminDossiersIndexRoute
  '/expert/dossiers/': typeof ExpertDossiersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/a-propos'
    | '/admin'
    | '/auth'
    | '/comment-ca-marche'
    | '/contact'
    | '/dashboard'
    | '/espace'
    | '/expert'
    | '/expert-assure-bordeaux'
    | '/expert-assure-lyon'
    | '/expert-assure-marseille'
    | '/expert-assure-paris'
    | '/expert-assure-toulouse'
    | '/experts'
    | '/faq'
    | '/guides'
    | '/inscription-expert'
    | '/login'
    | '/onboarding'
    | '/reset-password'
    | '/sinistres'
    | '/tarifs'
    | '/villes'
    | '/admin/dossiers'
    | '/admin/experts'
    | '/admin/facturation'
    | '/admin/reporting'
    | '/admin/utilisateurs'
    | '/dashboard/nouveau'
    | '/espace/dossiers'
    | '/espace/nouveau'
    | '/expert/dossiers'
    | '/expert/profil'
    | '/guides/assureur-refuse-payer'
    | '/guides/declarer-sinistre-assurance'
    | '/guides/delai-prescription-assurance'
    | '/guides/expert-assure'
    | '/guides/proces-verbal-expertise-assurance'
    | '/guides/regle-proportionnelle-assurance'
    | '/guides/sous-indemnisation'
    | '/guides/vetuste-assurance'
    | '/sinistres/catastrophe-naturelle'
    | '/sinistres/degat-des-eaux'
    | '/sinistres/dommages-electriques'
    | '/sinistres/incendie'
    | '/sinistres/tempete'
    | '/admin/'
    | '/dashboard/'
    | '/expert/'
    | '/guides/'
    | '/sinistres/'
    | '/admin/dossiers/$dossierId'
    | '/admin/utilisateurs/$userId'
    | '/dashboard/dossiers/$id'
    | '/espace/dossiers/$caseId'
    | '/expert/dossiers/$id'
    | '/admin/dossiers/'
    | '/expert/dossiers/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/a-propos'
    | '/auth'
    | '/comment-ca-marche'
    | '/contact'
    | '/espace'
    | '/expert-assure-bordeaux'
    | '/expert-assure-lyon'
    | '/expert-assure-marseille'
    | '/expert-assure-paris'
    | '/expert-assure-toulouse'
    | '/experts'
    | '/faq'
    | '/inscription-expert'
    | '/login'
    | '/onboarding'
    | '/reset-password'
    | '/tarifs'
    | '/villes'
    | '/admin/experts'
    | '/admin/facturation'
    | '/admin/reporting'
    | '/admin/utilisateurs'
    | '/dashboard/nouveau'
    | '/espace/dossiers'
    | '/espace/nouveau'
    | '/expert/profil'
    | '/guides/assureur-refuse-payer'
    | '/guides/declarer-sinistre-assurance'
    | '/guides/delai-prescription-assurance'
    | '/guides/expert-assure'
    | '/guides/proces-verbal-expertise-assurance'
    | '/guides/regle-proportionnelle-assurance'
    | '/guides/sous-indemnisation'
    | '/guides/vetuste-assurance'
    | '/sinistres/catastrophe-naturelle'
    | '/sinistres/degat-des-eaux'
    | '/sinistres/dommages-electriques'
    | '/sinistres/incendie'
    | '/sinistres/tempete'
    | '/admin'
    | '/dashboard'
    | '/expert'
    | '/guides'
    | '/sinistres'
    | '/admin/dossiers/$dossierId'
    | '/admin/utilisateurs/$userId'
    | '/dashboard/dossiers/$id'
    | '/espace/dossiers/$caseId'
    | '/expert/dossiers/$id'
    | '/admin/dossiers'
    | '/expert/dossiers'
  id:
    | '__root__'
    | '/'
    | '/a-propos'
    | '/admin'
    | '/auth'
    | '/comment-ca-marche'
    | '/contact'
    | '/dashboard'
    | '/espace'
    | '/expert'
    | '/expert-assure-bordeaux'
    | '/expert-assure-lyon'
    | '/expert-assure-marseille'
    | '/expert-assure-paris'
    | '/expert-assure-toulouse'
    | '/experts'
    | '/faq'
    | '/guides'
    | '/inscription-expert'
    | '/login'
    | '/onboarding'
    | '/reset-password'
    | '/sinistres'
    | '/tarifs'
    | '/villes'
    | '/admin/dossiers'
    | '/admin/experts'
    | '/admin/facturation'
    | '/admin/reporting'
    | '/admin/utilisateurs'
    | '/dashboard/nouveau'
    | '/espace/dossiers'
    | '/espace/nouveau'
    | '/expert/dossiers'
    | '/expert/profil'
    | '/guides/assureur-refuse-payer'
    | '/guides/declarer-sinistre-assurance'
    | '/guides/delai-prescription-assurance'
    | '/guides/expert-assure'
    | '/guides/proces-verbal-expertise-assurance'
    | '/guides/regle-proportionnelle-assurance'
    | '/guides/sous-indemnisation'
    | '/guides/vetuste-assurance'
    | '/sinistres/catastrophe-naturelle'
    | '/sinistres/degat-des-eaux'
    | '/sinistres/dommages-electriques'
    | '/sinistres/incendie'
    | '/sinistres/tempete'
    | '/admin/'
    | '/dashboard/'
    | '/expert/'
    | '/guides/'
    | '/sinistres/'
    | '/admin/dossiers/$dossierId'
    | '/admin_/utilisateurs/$userId'
    | '/dashboard/dossiers/$id'
    | '/espace/dossiers/$caseId'
    | '/expert/dossiers/$id'
    | '/admin/dossiers/'
    | '/expert/dossiers/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AProposRoute: typeof AProposRoute
  AdminRoute: typeof AdminRouteWithChildren
  AuthRoute: typeof AuthRoute
  CommentCaMarcheRoute: typeof CommentCaMarcheRoute
  ContactRoute: typeof ContactRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  EspaceRoute: typeof EspaceRouteWithChildren
  ExpertRoute: typeof ExpertRouteWithChildren
  ExpertAssureBordeauxRoute: typeof ExpertAssureBordeauxRoute
  ExpertAssureLyonRoute: typeof ExpertAssureLyonRoute
  ExpertAssureMarseilleRoute: typeof ExpertAssureMarseilleRoute
  ExpertAssureParisRoute: typeof ExpertAssureParisRoute
  ExpertAssureToulouseRoute: typeof ExpertAssureToulouseRoute
  ExpertsRoute: typeof ExpertsRoute
  FaqRoute: typeof FaqRoute
  GuidesRoute: typeof GuidesRouteWithChildren
  InscriptionExpertRoute: typeof InscriptionExpertRoute
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SinistresRoute: typeof SinistresRouteWithChildren
  TarifsRoute: typeof TarifsRoute
  VillesRoute: typeof VillesRoute
  AdminUtilisateursUserIdRoute: typeof AdminUtilisateursUserIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/villes': {
      id: '/villes'
      path: '/villes'
      fullPath: '/villes'
      preLoaderRoute: typeof VillesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tarifs': {
      id: '/tarifs'
      path: '/tarifs'
      fullPath: '/tarifs'
      preLoaderRoute: typeof TarifsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sinistres': {
      id: '/sinistres'
      path: '/sinistres'
      fullPath: '/sinistres'
      preLoaderRoute: typeof SinistresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inscription-expert': {
      id: '/inscription-expert'
      path: '/inscription-expert'
      fullPath: '/inscription-expert'
      preLoaderRoute: typeof InscriptionExpertRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides': {
      id: '/guides'
      path: '/guides'
      fullPath: '/guides'
      preLoaderRoute: typeof GuidesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/experts': {
      id: '/experts'
      path: '/experts'
      fullPath: '/experts'
      preLoaderRoute: typeof ExpertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/expert-assure-toulouse': {
      id: '/expert-assure-toulouse'
      path: '/expert-assure-toulouse'
      fullPath: '/expert-assure-toulouse'
      preLoaderRoute: typeof ExpertAssureToulouseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/expert-assure-paris': {
      id: '/expert-assure-paris'
      path: '/expert-assure-paris'
      fullPath: '/expert-assure-paris'
      preLoaderRoute: typeof ExpertAssureParisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/expert-assure-marseille': {
      id: '/expert-assure-marseille'
      path: '/expert-assure-marseille'
      fullPath: '/expert-assure-marseille'
      preLoaderRoute: typeof ExpertAssureMarseilleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/expert-assure-lyon': {
      id: '/expert-assure-lyon'
      path: '/expert-assure-lyon'
      fullPath: '/expert-assure-lyon'
      preLoaderRoute: typeof ExpertAssureLyonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/expert-assure-bordeaux': {
      id: '/expert-assure-bordeaux'
      path: '/expert-assure-bordeaux'
      fullPath: '/expert-assure-bordeaux'
      preLoaderRoute: typeof ExpertAssureBordeauxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/expert': {
      id: '/expert'
      path: '/expert'
      fullPath: '/expert'
      preLoaderRoute: typeof ExpertRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/espace': {
      id: '/espace'
      path: '/espace'
      fullPath: '/espace'
      preLoaderRoute: typeof EspaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comment-ca-marche': {
      id: '/comment-ca-marche'
      path: '/comment-ca-marche'
      fullPath: '/comment-ca-marche'
      preLoaderRoute: typeof CommentCaMarcheRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/a-propos': {
      id: '/a-propos'
      path: '/a-propos'
      fullPath: '/a-propos'
      preLoaderRoute: typeof AProposRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sinistres/': {
      id: '/sinistres/'
      path: '/'
      fullPath: '/sinistres/'
      preLoaderRoute: typeof SinistresIndexRouteImport
      parentRoute: typeof SinistresRoute
    }
    '/guides/': {
      id: '/guides/'
      path: '/'
      fullPath: '/guides/'
      preLoaderRoute: typeof GuidesIndexRouteImport
      parentRoute: typeof GuidesRoute
    }
    '/expert/': {
      id: '/expert/'
      path: '/'
      fullPath: '/expert/'
      preLoaderRoute: typeof ExpertIndexRouteImport
      parentRoute: typeof ExpertRoute
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/sinistres/tempete': {
      id: '/sinistres/tempete'
      path: '/tempete'
      fullPath: '/sinistres/tempete'
      preLoaderRoute: typeof SinistresTempeteRouteImport
      parentRoute: typeof SinistresRoute
    }
    '/sinistres/incendie': {
      id: '/sinistres/incendie'
      path: '/incendie'
      fullPath: '/sinistres/incendie'
      preLoaderRoute: typeof SinistresIncendieRouteImport
      parentRoute: typeof SinistresRoute
    }
    '/sinistres/dommages-electriques': {
      id: '/sinistres/dommages-electriques'
      path: '/dommages-electriques'
      fullPath: '/sinistres/dommages-electriques'
      preLoaderRoute: typeof SinistresDommagesElectriquesRouteImport
      parentRoute: typeof SinistresRoute
    }
    '/sinistres/degat-des-eaux': {
      id: '/sinistres/degat-des-eaux'
      path: '/degat-des-eaux'
      fullPath: '/sinistres/degat-des-eaux'
      preLoaderRoute: typeof SinistresDegatDesEauxRouteImport
      parentRoute: typeof SinistresRoute
    }
    '/sinistres/catastrophe-naturelle': {
      id: '/sinistres/catastrophe-naturelle'
      path: '/catastrophe-naturelle'
      fullPath: '/sinistres/catastrophe-naturelle'
      preLoaderRoute: typeof SinistresCatastropheNaturelleRouteImport
      parentRoute: typeof SinistresRoute
    }
    '/guides/vetuste-assurance': {
      id: '/guides/vetuste-assurance'
      path: '/vetuste-assurance'
      fullPath: '/guides/vetuste-assurance'
      preLoaderRoute: typeof GuidesVetusteAssuranceRouteImport
      parentRoute: typeof GuidesRoute
    }
    '/guides/sous-indemnisation': {
      id: '/guides/sous-indemnisation'
      path: '/sous-indemnisation'
      fullPath: '/guides/sous-indemnisation'
      preLoaderRoute: typeof GuidesSousIndemnisationRouteImport
      parentRoute: typeof GuidesRoute
    }
    '/guides/regle-proportionnelle-assurance': {
      id: '/guides/regle-proportionnelle-assurance'
      path: '/regle-proportionnelle-assurance'
      fullPath: '/guides/regle-proportionnelle-assurance'
      preLoaderRoute: typeof GuidesRegleProportionnelleAssuranceRouteImport
      parentRoute: typeof GuidesRoute
    }
    '/guides/proces-verbal-expertise-assurance': {
      id: '/guides/proces-verbal-expertise-assurance'
      path: '/proces-verbal-expertise-assurance'
      fullPath: '/guides/proces-verbal-expertise-assurance'
      preLoaderRoute: typeof GuidesProcesVerbalExpertiseAssuranceRouteImport
      parentRoute: typeof GuidesRoute
    }
    '/guides/expert-assure': {
      id: '/guides/expert-assure'
      path: '/expert-assure'
      fullPath: '/guides/expert-assure'
      preLoaderRoute: typeof GuidesExpertAssureRouteImport
      parentRoute: typeof GuidesRoute
    }
    '/guides/delai-prescription-assurance': {
      id: '/guides/delai-prescription-assurance'
      path: '/delai-prescription-assurance'
      fullPath: '/guides/delai-prescription-assurance'
      preLoaderRoute: typeof GuidesDelaiPrescriptionAssuranceRouteImport
      parentRoute: typeof GuidesRoute
    }
    '/guides/declarer-sinistre-assurance': {
      id: '/guides/declarer-sinistre-assurance'
      path: '/declarer-sinistre-assurance'
      fullPath: '/guides/declarer-sinistre-assurance'
      preLoaderRoute: typeof GuidesDeclarerSinistreAssuranceRouteImport
      parentRoute: typeof GuidesRoute
    }
    '/guides/assureur-refuse-payer': {
      id: '/guides/assureur-refuse-payer'
      path: '/assureur-refuse-payer'
      fullPath: '/guides/assureur-refuse-payer'
      preLoaderRoute: typeof GuidesAssureurRefusePayerRouteImport
      parentRoute: typeof GuidesRoute
    }
    '/expert/profil': {
      id: '/expert/profil'
      path: '/profil'
      fullPath: '/expert/profil'
      preLoaderRoute: typeof ExpertProfilRouteImport
      parentRoute: typeof ExpertRoute
    }
    '/expert/dossiers': {
      id: '/expert/dossiers'
      path: '/dossiers'
      fullPath: '/expert/dossiers'
      preLoaderRoute: typeof ExpertDossiersRouteImport
      parentRoute: typeof ExpertRoute
    }
    '/espace/nouveau': {
      id: '/espace/nouveau'
      path: '/nouveau'
      fullPath: '/espace/nouveau'
      preLoaderRoute: typeof EspaceNouveauRouteImport
      parentRoute: typeof EspaceRoute
    }
    '/espace/dossiers': {
      id: '/espace/dossiers'
      path: '/dossiers'
      fullPath: '/espace/dossiers'
      preLoaderRoute: typeof EspaceDossiersRouteImport
      parentRoute: typeof EspaceRoute
    }
    '/dashboard/nouveau': {
      id: '/dashboard/nouveau'
      path: '/nouveau'
      fullPath: '/dashboard/nouveau'
      preLoaderRoute: typeof DashboardNouveauRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/admin/utilisateurs': {
      id: '/admin/utilisateurs'
      path: '/utilisateurs'
      fullPath: '/admin/utilisateurs'
      preLoaderRoute: typeof AdminUtilisateursRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reporting': {
      id: '/admin/reporting'
      path: '/reporting'
      fullPath: '/admin/reporting'
      preLoaderRoute: typeof AdminReportingRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/facturation': {
      id: '/admin/facturation'
      path: '/facturation'
      fullPath: '/admin/facturation'
      preLoaderRoute: typeof AdminFacturationRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/experts': {
      id: '/admin/experts'
      path: '/experts'
      fullPath: '/admin/experts'
      preLoaderRoute: typeof AdminExpertsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/dossiers': {
      id: '/admin/dossiers'
      path: '/dossiers'
      fullPath: '/admin/dossiers'
      preLoaderRoute: typeof AdminDossiersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/expert/dossiers/': {
      id: '/expert/dossiers/'
      path: '/'
      fullPath: '/expert/dossiers/'
      preLoaderRoute: typeof ExpertDossiersIndexRouteImport
      parentRoute: typeof ExpertDossiersRoute
    }
    '/admin/dossiers/': {
      id: '/admin/dossiers/'
      path: '/'
      fullPath: '/admin/dossiers/'
      preLoaderRoute: typeof AdminDossiersIndexRouteImport
      parentRoute: typeof AdminDossiersRoute
    }
    '/expert/dossiers/$id': {
      id: '/expert/dossiers/$id'
      path: '/$id'
      fullPath: '/expert/dossiers/$id'
      preLoaderRoute: typeof ExpertDossiersIdRouteImport
      parentRoute: typeof ExpertDossiersRoute
    }
    '/espace/dossiers/$caseId': {
      id: '/espace/dossiers/$caseId'
      path: '/$caseId'
      fullPath: '/espace/dossiers/$caseId'
      preLoaderRoute: typeof EspaceDossiersCaseIdRouteImport
      parentRoute: typeof EspaceDossiersRoute
    }
    '/dashboard/dossiers/$id': {
      id: '/dashboard/dossiers/$id'
      path: '/dossiers/$id'
      fullPath: '/dashboard/dossiers/$id'
      preLoaderRoute: typeof DashboardDossiersIdRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/admin_/utilisateurs/$userId': {
      id: '/admin_/utilisateurs/$userId'
      path: '/admin/utilisateurs/$userId'
      fullPath: '/admin/utilisateurs/$userId'
      preLoaderRoute: typeof AdminUtilisateursUserIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/dossiers/$dossierId': {
      id: '/admin/dossiers/$dossierId'
      path: '/$dossierId'
      fullPath: '/admin/dossiers/$dossierId'
      preLoaderRoute: typeof AdminDossiersDossierIdRouteImport
      parentRoute: typeof AdminDossiersRoute
    }
  }
}

interface AdminDossiersRouteChildren {
  AdminDossiersDossierIdRoute: typeof AdminDossiersDossierIdRoute
  AdminDossiersIndexRoute: typeof AdminDossiersIndexRoute
}

const AdminDossiersRouteChildren: AdminDossiersRouteChildren = {
  AdminDossiersDossierIdRoute: AdminDossiersDossierIdRoute,
  AdminDossiersIndexRoute: AdminDossiersIndexRoute,
}

const AdminDossiersRouteWithChildren = AdminDossiersRoute._addFileChildren(
  AdminDossiersRouteChildren,
)

interface AdminRouteChildren {
  AdminDossiersRoute: typeof AdminDossiersRouteWithChildren
  AdminExpertsRoute: typeof AdminExpertsRoute
  AdminFacturationRoute: typeof AdminFacturationRoute
  AdminReportingRoute: typeof AdminReportingRoute
  AdminUtilisateursRoute: typeof AdminUtilisateursRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminDossiersRoute: AdminDossiersRouteWithChildren,
  AdminExpertsRoute: AdminExpertsRoute,
  AdminFacturationRoute: AdminFacturationRoute,
  AdminReportingRoute: AdminReportingRoute,
  AdminUtilisateursRoute: AdminUtilisateursRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface DashboardRouteChildren {
  DashboardNouveauRoute: typeof DashboardNouveauRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardDossiersIdRoute: typeof DashboardDossiersIdRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardNouveauRoute: DashboardNouveauRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardDossiersIdRoute: DashboardDossiersIdRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

interface EspaceDossiersRouteChildren {
  EspaceDossiersCaseIdRoute: typeof EspaceDossiersCaseIdRoute
}

const EspaceDossiersRouteChildren: EspaceDossiersRouteChildren = {
  EspaceDossiersCaseIdRoute: EspaceDossiersCaseIdRoute,
}

const EspaceDossiersRouteWithChildren = EspaceDossiersRoute._addFileChildren(
  EspaceDossiersRouteChildren,
)

interface EspaceRouteChildren {
  EspaceDossiersRoute: typeof EspaceDossiersRouteWithChildren
  EspaceNouveauRoute: typeof EspaceNouveauRoute
}

const EspaceRouteChildren: EspaceRouteChildren = {
  EspaceDossiersRoute: EspaceDossiersRouteWithChildren,
  EspaceNouveauRoute: EspaceNouveauRoute,
}

const EspaceRouteWithChildren =
  EspaceRoute._addFileChildren(EspaceRouteChildren)

interface ExpertDossiersRouteChildren {
  ExpertDossiersIdRoute: typeof ExpertDossiersIdRoute
  ExpertDossiersIndexRoute: typeof ExpertDossiersIndexRoute
}

const ExpertDossiersRouteChildren: ExpertDossiersRouteChildren = {
  ExpertDossiersIdRoute: ExpertDossiersIdRoute,
  ExpertDossiersIndexRoute: ExpertDossiersIndexRoute,
}

const ExpertDossiersRouteWithChildren = ExpertDossiersRoute._addFileChildren(
  ExpertDossiersRouteChildren,
)

interface ExpertRouteChildren {
  ExpertDossiersRoute: typeof ExpertDossiersRouteWithChildren
  ExpertProfilRoute: typeof ExpertProfilRoute
  ExpertIndexRoute: typeof ExpertIndexRoute
}

const ExpertRouteChildren: ExpertRouteChildren = {
  ExpertDossiersRoute: ExpertDossiersRouteWithChildren,
  ExpertProfilRoute: ExpertProfilRoute,
  ExpertIndexRoute: ExpertIndexRoute,
}

const ExpertRouteWithChildren =
  ExpertRoute._addFileChildren(ExpertRouteChildren)

interface GuidesRouteChildren {
  GuidesAssureurRefusePayerRoute: typeof GuidesAssureurRefusePayerRoute
  GuidesDeclarerSinistreAssuranceRoute: typeof GuidesDeclarerSinistreAssuranceRoute
  GuidesDelaiPrescriptionAssuranceRoute: typeof GuidesDelaiPrescriptionAssuranceRoute
  GuidesExpertAssureRoute: typeof GuidesExpertAssureRoute
  GuidesProcesVerbalExpertiseAssuranceRoute: typeof GuidesProcesVerbalExpertiseAssuranceRoute
  GuidesRegleProportionnelleAssuranceRoute: typeof GuidesRegleProportionnelleAssuranceRoute
  GuidesSousIndemnisationRoute: typeof GuidesSousIndemnisationRoute
  GuidesVetusteAssuranceRoute: typeof GuidesVetusteAssuranceRoute
  GuidesIndexRoute: typeof GuidesIndexRoute
}

const GuidesRouteChildren: GuidesRouteChildren = {
  GuidesAssureurRefusePayerRoute: GuidesAssureurRefusePayerRoute,
  GuidesDeclarerSinistreAssuranceRoute: GuidesDeclarerSinistreAssuranceRoute,
  GuidesDelaiPrescriptionAssuranceRoute: GuidesDelaiPrescriptionAssuranceRoute,
  GuidesExpertAssureRoute: GuidesExpertAssureRoute,
  GuidesProcesVerbalExpertiseAssuranceRoute:
    GuidesProcesVerbalExpertiseAssuranceRoute,
  GuidesRegleProportionnelleAssuranceRoute:
    GuidesRegleProportionnelleAssuranceRoute,
  GuidesSousIndemnisationRoute: GuidesSousIndemnisationRoute,
  GuidesVetusteAssuranceRoute: GuidesVetusteAssuranceRoute,
  GuidesIndexRoute: GuidesIndexRoute,
}

const GuidesRouteWithChildren =
  GuidesRoute._addFileChildren(GuidesRouteChildren)

interface SinistresRouteChildren {
  SinistresCatastropheNaturelleRoute: typeof SinistresCatastropheNaturelleRoute
  SinistresDegatDesEauxRoute: typeof SinistresDegatDesEauxRoute
  SinistresDommagesElectriquesRoute: typeof SinistresDommagesElectriquesRoute
  SinistresIncendieRoute: typeof SinistresIncendieRoute
  SinistresTempeteRoute: typeof SinistresTempeteRoute
  SinistresIndexRoute: typeof SinistresIndexRoute
}

const SinistresRouteChildren: SinistresRouteChildren = {
  SinistresCatastropheNaturelleRoute: SinistresCatastropheNaturelleRoute,
  SinistresDegatDesEauxRoute: SinistresDegatDesEauxRoute,
  SinistresDommagesElectriquesRoute: SinistresDommagesElectriquesRoute,
  SinistresIncendieRoute: SinistresIncendieRoute,
  SinistresTempeteRoute: SinistresTempeteRoute,
  SinistresIndexRoute: SinistresIndexRoute,
}

const SinistresRouteWithChildren = SinistresRoute._addFileChildren(
  SinistresRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AProposRoute: AProposRoute,
  AdminRoute: AdminRouteWithChildren,
  AuthRoute: AuthRoute,
  CommentCaMarcheRoute: CommentCaMarcheRoute,
  ContactRoute: ContactRoute,
  DashboardRoute: DashboardRouteWithChildren,
  EspaceRoute: EspaceRouteWithChildren,
  ExpertRoute: ExpertRouteWithChildren,
  ExpertAssureBordeauxRoute: ExpertAssureBordeauxRoute,
  ExpertAssureLyonRoute: ExpertAssureLyonRoute,
  ExpertAssureMarseilleRoute: ExpertAssureMarseilleRoute,
  ExpertAssureParisRoute: ExpertAssureParisRoute,
  ExpertAssureToulouseRoute: ExpertAssureToulouseRoute,
  ExpertsRoute: ExpertsRoute,
  FaqRoute: FaqRoute,
  GuidesRoute: GuidesRouteWithChildren,
  InscriptionExpertRoute: InscriptionExpertRoute,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SinistresRoute: SinistresRouteWithChildren,
  TarifsRoute: TarifsRoute,
  VillesRoute: VillesRoute,
  AdminUtilisateursUserIdRoute: AdminUtilisateursUserIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
