/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TarifsRouteImport } from './routes/tarifs'
import { Route as SinistresRouteImport } from './routes/sinistres'
import { Route as LoginRouteImport } from './routes/login'
import { Route as InscriptionExpertRouteImport } from './routes/inscription-expert'
import { Route as GuidesRouteImport } from './routes/guides'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as ExpertRouteImport } from './routes/expert'
import { Route as EspaceRouteImport } from './routes/espace'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CommentCaMarcheRouteImport } from './routes/comment-ca-marche'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AProposRouteImport } from './routes/a-propos'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GuidesIndexRouteImport } from './routes/guides.index'
import { Route as ExpertIndexRouteImport } from './routes/expert.index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as GuidesExpertAssureRouteImport } from './routes/guides.expert-assure'
import { Route as GuidesAssureurRefusePayerRouteImport } from './routes/guides.assureur-refuse-payer'
import { Route as EspaceNouveauRouteImport } from './routes/espace.nouveau'
import { Route as EspaceDossiersRouteImport } from './routes/espace.dossiers'
import { Route as DashboardNouveauRouteImport } from './routes/dashboard.nouveau'
import { Route as ExpertDossiersIdRouteImport } from './routes/expert.dossiers.$id'
import { Route as EspaceDossiersCaseIdRouteImport } from './routes/espace.dossiers.$caseId'
import { Route as DashboardDossiersIdRouteImport } from './routes/dashboard.dossiers.$id'

const TarifsRoute = TarifsRouteImport.update({
  id: '/tarifs',
  path: '/tarifs',
  getParentRoute: () => rootRouteImport,
} as any)
const SinistresRoute = SinistresRouteImport.update({
  id: '/sinistres',
  path: '/sinistres',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const InscriptionExpertRoute = InscriptionExpertRouteImport.update({
  id: '/inscription-expert',
  path: '/inscription-expert',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidesRoute = GuidesRouteImport.update({
  id: '/guides',
  path: '/guides',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const ExpertRoute = ExpertRouteImport.update({
  id: '/expert',
  path: '/expert',
  getParentRoute: () => rootRouteImport,
} as any)
const EspaceRoute = EspaceRouteImport.update({
  id: '/espace',
  path: '/espace',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CommentCaMarcheRoute = CommentCaMarcheRouteImport.update({
  id: '/comment-ca-marche',
  path: '/comment-ca-marche',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AProposRoute = AProposRouteImport.update({
  id: '/a-propos',
  path: '/a-propos',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidesIndexRoute = GuidesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => GuidesRoute,
} as any)
const ExpertIndexRoute = ExpertIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ExpertRoute,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const GuidesExpertAssureRoute = GuidesExpertAssureRouteImport.update({
  id: '/expert-assure',
  path: '/expert-assure',
  getParentRoute: () => GuidesRoute,
} as any)
const GuidesAssureurRefusePayerRoute =
  GuidesAssureurRefusePayerRouteImport.update({
    id: '/assureur-refuse-payer',
    path: '/assureur-refuse-payer',
    getParentRoute: () => GuidesRoute,
  } as any)
const EspaceNouveauRoute = EspaceNouveauRouteImport.update({
  id: '/nouveau',
  path: '/nouveau',
  getParentRoute: () => EspaceRoute,
} as any)
const EspaceDossiersRoute = EspaceDossiersRouteImport.update({
  id: '/dossiers',
  path: '/dossiers',
  getParentRoute: () => EspaceRoute,
} as any)
const DashboardNouveauRoute = DashboardNouveauRouteImport.update({
  id: '/nouveau',
  path: '/nouveau',
  getParentRoute: () => DashboardRoute,
} as any)
const ExpertDossiersIdRoute = ExpertDossiersIdRouteImport.update({
  id: '/dossiers/$id',
  path: '/dossiers/$id',
  getParentRoute: () => ExpertRoute,
} as any)
const EspaceDossiersCaseIdRoute = EspaceDossiersCaseIdRouteImport.update({
  id: '/$caseId',
  path: '/$caseId',
  getParentRoute: () => EspaceDossiersRoute,
} as any)
const DashboardDossiersIdRoute = DashboardDossiersIdRouteImport.update({
  id: '/dossiers/$id',
  path: '/dossiers/$id',
  getParentRoute: () => DashboardRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/comment-ca-marche': typeof CommentCaMarcheRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/espace': typeof EspaceRouteWithChildren
  '/expert': typeof ExpertRouteWithChildren
  '/faq': typeof FaqRoute
  '/guides': typeof GuidesRouteWithChildren
  '/inscription-expert': typeof InscriptionExpertRoute
  '/login': typeof LoginRoute
  '/sinistres': typeof SinistresRoute
  '/tarifs': typeof TarifsRoute
  '/dashboard/nouveau': typeof DashboardNouveauRoute
  '/espace/dossiers': typeof EspaceDossiersRouteWithChildren
  '/espace/nouveau': typeof EspaceNouveauRoute
  '/guides/assureur-refuse-payer': typeof GuidesAssureurRefusePayerRoute
  '/guides/expert-assure': typeof GuidesExpertAssureRoute
  '/admin/': typeof AdminIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/expert/': typeof ExpertIndexRoute
  '/guides/': typeof GuidesIndexRoute
  '/dashboard/dossiers/$id': typeof DashboardDossiersIdRoute
  '/espace/dossiers/$caseId': typeof EspaceDossiersCaseIdRoute
  '/expert/dossiers/$id': typeof ExpertDossiersIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/auth': typeof AuthRoute
  '/comment-ca-marche': typeof CommentCaMarcheRoute
  '/contact': typeof ContactRoute
  '/espace': typeof EspaceRouteWithChildren
  '/faq': typeof FaqRoute
  '/inscription-expert': typeof InscriptionExpertRoute
  '/login': typeof LoginRoute
  '/sinistres': typeof SinistresRoute
  '/tarifs': typeof TarifsRoute
  '/dashboard/nouveau': typeof DashboardNouveauRoute
  '/espace/dossiers': typeof EspaceDossiersRouteWithChildren
  '/espace/nouveau': typeof EspaceNouveauRoute
  '/guides/assureur-refuse-payer': typeof GuidesAssureurRefusePayerRoute
  '/guides/expert-assure': typeof GuidesExpertAssureRoute
  '/admin': typeof AdminIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/expert': typeof ExpertIndexRoute
  '/guides': typeof GuidesIndexRoute
  '/dashboard/dossiers/$id': typeof DashboardDossiersIdRoute
  '/espace/dossiers/$caseId': typeof EspaceDossiersCaseIdRoute
  '/expert/dossiers/$id': typeof ExpertDossiersIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/comment-ca-marche': typeof CommentCaMarcheRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/espace': typeof EspaceRouteWithChildren
  '/expert': typeof ExpertRouteWithChildren
  '/faq': typeof FaqRoute
  '/guides': typeof GuidesRouteWithChildren
  '/inscription-expert': typeof InscriptionExpertRoute
  '/login': typeof LoginRoute
  '/sinistres': typeof SinistresRoute
  '/tarifs': typeof TarifsRoute
  '/dashboard/nouveau': typeof DashboardNouveauRoute
  '/espace/dossiers': typeof EspaceDossiersRouteWithChildren
  '/espace/nouveau': typeof EspaceNouveauRoute
  '/guides/assureur-refuse-payer': typeof GuidesAssureurRefusePayerRoute
  '/guides/expert-assure': typeof GuidesExpertAssureRoute
  '/admin/': typeof AdminIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/expert/': typeof ExpertIndexRoute
  '/guides/': typeof GuidesIndexRoute
  '/dashboard/dossiers/$id': typeof DashboardDossiersIdRoute
  '/espace/dossiers/$caseId': typeof EspaceDossiersCaseIdRoute
  '/expert/dossiers/$id': typeof ExpertDossiersIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/a-propos'
    | '/admin'
    | '/auth'
    | '/comment-ca-marche'
    | '/contact'
    | '/dashboard'
    | '/espace'
    | '/expert'
    | '/faq'
    | '/guides'
    | '/inscription-expert'
    | '/login'
    | '/sinistres'
    | '/tarifs'
    | '/dashboard/nouveau'
    | '/espace/dossiers'
    | '/espace/nouveau'
    | '/guides/assureur-refuse-payer'
    | '/guides/expert-assure'
    | '/admin/'
    | '/dashboard/'
    | '/expert/'
    | '/guides/'
    | '/dashboard/dossiers/$id'
    | '/espace/dossiers/$caseId'
    | '/expert/dossiers/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/a-propos'
    | '/auth'
    | '/comment-ca-marche'
    | '/contact'
    | '/espace'
    | '/faq'
    | '/inscription-expert'
    | '/login'
    | '/sinistres'
    | '/tarifs'
    | '/dashboard/nouveau'
    | '/espace/dossiers'
    | '/espace/nouveau'
    | '/guides/assureur-refuse-payer'
    | '/guides/expert-assure'
    | '/admin'
    | '/dashboard'
    | '/expert'
    | '/guides'
    | '/dashboard/dossiers/$id'
    | '/espace/dossiers/$caseId'
    | '/expert/dossiers/$id'
  id:
    | '__root__'
    | '/'
    | '/a-propos'
    | '/admin'
    | '/auth'
    | '/comment-ca-marche'
    | '/contact'
    | '/dashboard'
    | '/espace'
    | '/expert'
    | '/faq'
    | '/guides'
    | '/inscription-expert'
    | '/login'
    | '/sinistres'
    | '/tarifs'
    | '/dashboard/nouveau'
    | '/espace/dossiers'
    | '/espace/nouveau'
    | '/guides/assureur-refuse-payer'
    | '/guides/expert-assure'
    | '/admin/'
    | '/dashboard/'
    | '/expert/'
    | '/guides/'
    | '/dashboard/dossiers/$id'
    | '/espace/dossiers/$caseId'
    | '/expert/dossiers/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AProposRoute: typeof AProposRoute
  AdminRoute: typeof AdminRouteWithChildren
  AuthRoute: typeof AuthRoute
  CommentCaMarcheRoute: typeof CommentCaMarcheRoute
  ContactRoute: typeof ContactRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  EspaceRoute: typeof EspaceRouteWithChildren
  ExpertRoute: typeof ExpertRouteWithChildren
  FaqRoute: typeof FaqRoute
  GuidesRoute: typeof GuidesRouteWithChildren
  InscriptionExpertRoute: typeof InscriptionExpertRoute
  LoginRoute: typeof LoginRoute
  SinistresRoute: typeof SinistresRoute
  TarifsRoute: typeof TarifsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tarifs': {
      id: '/tarifs'
      path: '/tarifs'
      fullPath: '/tarifs'
      preLoaderRoute: typeof TarifsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sinistres': {
      id: '/sinistres'
      path: '/sinistres'
      fullPath: '/sinistres'
      preLoaderRoute: typeof SinistresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inscription-expert': {
      id: '/inscription-expert'
      path: '/inscription-expert'
      fullPath: '/inscription-expert'
      preLoaderRoute: typeof InscriptionExpertRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides': {
      id: '/guides'
      path: '/guides'
      fullPath: '/guides'
      preLoaderRoute: typeof GuidesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/expert': {
      id: '/expert'
      path: '/expert'
      fullPath: '/expert'
      preLoaderRoute: typeof ExpertRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/espace': {
      id: '/espace'
      path: '/espace'
      fullPath: '/espace'
      preLoaderRoute: typeof EspaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comment-ca-marche': {
      id: '/comment-ca-marche'
      path: '/comment-ca-marche'
      fullPath: '/comment-ca-marche'
      preLoaderRoute: typeof CommentCaMarcheRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/a-propos': {
      id: '/a-propos'
      path: '/a-propos'
      fullPath: '/a-propos'
      preLoaderRoute: typeof AProposRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides/': {
      id: '/guides/'
      path: '/'
      fullPath: '/guides/'
      preLoaderRoute: typeof GuidesIndexRouteImport
      parentRoute: typeof GuidesRoute
    }
    '/expert/': {
      id: '/expert/'
      path: '/'
      fullPath: '/expert/'
      preLoaderRoute: typeof ExpertIndexRouteImport
      parentRoute: typeof ExpertRoute
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/guides/expert-assure': {
      id: '/guides/expert-assure'
      path: '/expert-assure'
      fullPath: '/guides/expert-assure'
      preLoaderRoute: typeof GuidesExpertAssureRouteImport
      parentRoute: typeof GuidesRoute
    }
    '/guides/assureur-refuse-payer': {
      id: '/guides/assureur-refuse-payer'
      path: '/assureur-refuse-payer'
      fullPath: '/guides/assureur-refuse-payer'
      preLoaderRoute: typeof GuidesAssureurRefusePayerRouteImport
      parentRoute: typeof GuidesRoute
    }
    '/espace/nouveau': {
      id: '/espace/nouveau'
      path: '/nouveau'
      fullPath: '/espace/nouveau'
      preLoaderRoute: typeof EspaceNouveauRouteImport
      parentRoute: typeof EspaceRoute
    }
    '/espace/dossiers': {
      id: '/espace/dossiers'
      path: '/dossiers'
      fullPath: '/espace/dossiers'
      preLoaderRoute: typeof EspaceDossiersRouteImport
      parentRoute: typeof EspaceRoute
    }
    '/dashboard/nouveau': {
      id: '/dashboard/nouveau'
      path: '/nouveau'
      fullPath: '/dashboard/nouveau'
      preLoaderRoute: typeof DashboardNouveauRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/expert/dossiers/$id': {
      id: '/expert/dossiers/$id'
      path: '/dossiers/$id'
      fullPath: '/expert/dossiers/$id'
      preLoaderRoute: typeof ExpertDossiersIdRouteImport
      parentRoute: typeof ExpertRoute
    }
    '/espace/dossiers/$caseId': {
      id: '/espace/dossiers/$caseId'
      path: '/$caseId'
      fullPath: '/espace/dossiers/$caseId'
      preLoaderRoute: typeof EspaceDossiersCaseIdRouteImport
      parentRoute: typeof EspaceDossiersRoute
    }
    '/dashboard/dossiers/$id': {
      id: '/dashboard/dossiers/$id'
      path: '/dossiers/$id'
      fullPath: '/dashboard/dossiers/$id'
      preLoaderRoute: typeof DashboardDossiersIdRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface AdminRouteChildren {
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface DashboardRouteChildren {
  DashboardNouveauRoute: typeof DashboardNouveauRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardDossiersIdRoute: typeof DashboardDossiersIdRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardNouveauRoute: DashboardNouveauRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardDossiersIdRoute: DashboardDossiersIdRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

interface EspaceDossiersRouteChildren {
  EspaceDossiersCaseIdRoute: typeof EspaceDossiersCaseIdRoute
}

const EspaceDossiersRouteChildren: EspaceDossiersRouteChildren = {
  EspaceDossiersCaseIdRoute: EspaceDossiersCaseIdRoute,
}

const EspaceDossiersRouteWithChildren = EspaceDossiersRoute._addFileChildren(
  EspaceDossiersRouteChildren,
)

interface EspaceRouteChildren {
  EspaceDossiersRoute: typeof EspaceDossiersRouteWithChildren
  EspaceNouveauRoute: typeof EspaceNouveauRoute
}

const EspaceRouteChildren: EspaceRouteChildren = {
  EspaceDossiersRoute: EspaceDossiersRouteWithChildren,
  EspaceNouveauRoute: EspaceNouveauRoute,
}

const EspaceRouteWithChildren =
  EspaceRoute._addFileChildren(EspaceRouteChildren)

interface ExpertRouteChildren {
  ExpertIndexRoute: typeof ExpertIndexRoute
  ExpertDossiersIdRoute: typeof ExpertDossiersIdRoute
}

const ExpertRouteChildren: ExpertRouteChildren = {
  ExpertIndexRoute: ExpertIndexRoute,
  ExpertDossiersIdRoute: ExpertDossiersIdRoute,
}

const ExpertRouteWithChildren =
  ExpertRoute._addFileChildren(ExpertRouteChildren)

interface GuidesRouteChildren {
  GuidesAssureurRefusePayerRoute: typeof GuidesAssureurRefusePayerRoute
  GuidesExpertAssureRoute: typeof GuidesExpertAssureRoute
  GuidesIndexRoute: typeof GuidesIndexRoute
}

const GuidesRouteChildren: GuidesRouteChildren = {
  GuidesAssureurRefusePayerRoute: GuidesAssureurRefusePayerRoute,
  GuidesExpertAssureRoute: GuidesExpertAssureRoute,
  GuidesIndexRoute: GuidesIndexRoute,
}

const GuidesRouteWithChildren =
  GuidesRoute._addFileChildren(GuidesRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AProposRoute: AProposRoute,
  AdminRoute: AdminRouteWithChildren,
  AuthRoute: AuthRoute,
  CommentCaMarcheRoute: CommentCaMarcheRoute,
  ContactRoute: ContactRoute,
  DashboardRoute: DashboardRouteWithChildren,
  EspaceRoute: EspaceRouteWithChildren,
  ExpertRoute: ExpertRouteWithChildren,
  FaqRoute: FaqRoute,
  GuidesRoute: GuidesRouteWithChildren,
  InscriptionExpertRoute: InscriptionExpertRoute,
  LoginRoute: LoginRoute,
  SinistresRoute: SinistresRoute,
  TarifsRoute: TarifsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
